version: "3"
services:
  grafana:
    image: grafana/grafana:5.1.0
    environment: 
      - GF_SERVER_ROOT_URL=http://192.168.99.100:3000
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - TZ="America/Bahia"
    ports:
      - 3000:3000
    user: "104"
  postgress:
    container_name: postgress
    image: postgres:9.6
    ports: 
      - 5432:5432
    environment:
      POSTGRESS_DB: fiapdb
      MYSQL_USER: postgres
      TZ: "America/Bahia"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"  
